// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYubGk0D_IKGiPLoLW3BScs2Mk_yHQ-vQ',
    appId: '1:963706864773:web:c3e08b93bfcb405e93d5ec',
    messagingSenderId: '963706864773',
    projectId: 'nyumba-app-2022',
    authDomain: 'nyumba-app-2022.firebaseapp.com',
    storageBucket: 'nyumba-app-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrkm4-njULL9Kzq6tNvqO-TTwAgAMIy70',
    appId: '1:963706864773:android:a52f5e4d3106ba2f93d5ec',
    messagingSenderId: '963706864773',
    projectId: 'nyumba-app-2022',
    storageBucket: 'nyumba-app-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDM1JvopwSWJ2phZdtQ-Wwqc9jBjvJ8Hc',
    appId: '1:963706864773:ios:007dd32d170e700493d5ec',
    messagingSenderId: '963706864773',
    projectId: 'nyumba-app-2022',
    storageBucket: 'nyumba-app-2022.appspot.com',
    iosClientId: '963706864773-1gjf6kki9e0dg8hk69dd4qdbfm2juvhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyumba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDM1JvopwSWJ2phZdtQ-Wwqc9jBjvJ8Hc',
    appId: '1:963706864773:ios:007dd32d170e700493d5ec',
    messagingSenderId: '963706864773',
    projectId: 'nyumba-app-2022',
    storageBucket: 'nyumba-app-2022.appspot.com',
    iosClientId: '963706864773-1gjf6kki9e0dg8hk69dd4qdbfm2juvhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyumba',
  );
}
